### ISSUE TITLE
Recent Discourse upgrade broke plugin

### ISSUE THREAD

**Issue by yunesj** [tareko/discourse-replyto-individual#3] opened 2021-08-12 19:51 UTC
This plugin was working great. Sometime after a recent Discourse upgrade, we noticed that replies-xyz@example.com was not being cc'ed to the forum emails.

**Comment by tareko** [comment] 2022-01-08 10:40
Hi Yunes,

Thank you for mentioning this. I'll take a look. Apologies for the delay getting back to you - this somehow didn't come up in my notifications.

tarek : )

**Comment by jdhildeb** [comment] 2022-01-12 04:44
FYI, I am interested in getting this plugin working again, because I need it for a group I'm migrating from mailman to discourse.

I am working to isolating which version of Discourse broke the plugin.

**Comment by jdhildeb** [comment] 2022-01-13 05:17
I tested all versions from 2.6.0 through 2.7.12.  I was not able to reproduce the reported issue.  Emails sent by discourse have "Reply-to" set to the email address of the user who posted, and "Cc" set to the reply address which discourse produces (e.g. replies+9f8fa1d73404afd2c854a50b4be991b9@example.org).  Based on this result, I believe the plugin is working as expected, however I have not been using this plugin in production -- it's new to me -- so I don't have prior experience to compare with.

I don't know whether it makes a difference or not, but I am using "mailing list mode".  

Related to this, I noticed that in one of the 2.7.X minor versions, the "mailing list mode" setting became invisible to end-users by default.  You need to go in to admin settings and turn OFF the "disable mailing list mode" setting.  After that it becomes visible to end-users.  This setting also says it "prevents any mailing list emails from being sent."  So this is just a guess, but I'm wondering whether an upgrade might have been affected by this new setting, which would cause outbound email to work differently.  I'd recommend checking this to make sure.

**Comment by tareko** [comment] 2022-08-27 08:50
This is now fixed and working. Apologies for the long delay - it completely fell off my radar over the past year and I didn't notice the bug in our relatively low-use discourse environment.

The roots of the bug were that the system for pushing the reply-to changed from applying a gsub to a gsub!, which meant that the "reply-to" line was getting killed when trying to replace replies. Also for some reason, there is a part of the code that kills all 2-part headers. I suspect this was done for a reason, but the conflicts mean that it broke the plugin.

Tested on the latest 2.9.0beta9. Let me know if there are any unexpected bugs.

**Closed by tareko** 2022-08-27 08:50 UTC
